{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
   - ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
{{- end }}
