{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rasa-common.names.fullname" . }}-allow-rasa-bot-redis-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rasa-bot
  policyTypes:
  - Egress
  egress:
{{- if and (not .Values.redis.external.enabled) (eq (include "rasa-common.redis.available" .) "true") }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: {{ template "rasa-common.psql.port" . }}
{{- else }}
  - ports:
    - protocol: TCP
      port: {{ template "rasa-common.psql.port" . }}
{{- end }}
---
{{- if and (not .Values.redis.external.enabled) (eq (include "rasa-common.redis.available" .) "true") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-rasa-bot-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: rasa-bot
    ports:
    - protocol: TCP
      port: {{ template "rasa-common.redis.port" . }}
{{- end }}
{{- end }}
