releases:
  - name: rasa-bot
    namespace: default
    chart: ../../charts/rasa-bot
    values:
      - applicationSettings:
          debugMode: true
      - initContainers:
        - name: download-model
          image: "busybox"
          command: ["/bin/sh", "-c"]
          args:
            - cd /app/models/ && wget https://github.com/RasaHQ/rasa-x-demo/blob/master/models/model.tar.gz?raw=true -O model.tar.gz
          volumeMounts:
            - mountPath: /app/models
              name: models
      - volumes:
        - name: models
          emptyDir: {}
      - volumeMounts:
          - mountPath: /app/models
            name: models
