releases:
  - name: rasa
    namespace: default
    chart: ../../charts/rasa
    values:
      - service:
          type: LoadBalancer
        replicaCount: 1
      - networkPolicy:
          enabled: true
          denyAll: true
      - nginx:
          enabled: false
          tls:
            enabled: true
            generateSelfSignedCert: true
      - applicationSettings:
          debugMode: true
          trainInitialModel: false
          credentials:
            enable: true
            additionalChannelCredentials:
              rest:
          endpoints:
            lockStore:
              enabled: true
            eventBroker:
              enabled: true
      - initContainers:
        - name: download-model
          image: "busybox"
          command: ["/bin/sh", "-c"]
          args:
            - cd /app/models/ && wget https://github.com/RasaHQ/rasa-x-demo/blob/master/models/model.tar.gz?raw=true -O model.tar.gz
          volumeMounts:
            - mountPath: /app/models
              name: models
      - volumes:
        - name: models
          emptyDir: {}
      - volumeMounts:
          - mountPath: /app/models
            name: models
      - ingress:
          enabled: true
      - rabbitmq:
          install: true
        redis:
          install: true
