releases:
  - name: rasa
    chart: ../../charts/rasa

    values:
      - service:
          type: LoadBalancer
      - nginx:
          tls:
            enabled: true
            generateSelfSignedCert: true
      - applicationSettings:
          rasaX:
            enabled: true
            url: "http://rasa-x-rasa-x:5002"
            useConfigEndpoint: false
          debugMode: true
          credentials:
            additionalChannelCredentials:
              rest:
          endpoints:
            eventBroker:
              customConfiguration:
                type: "pika"
                url: "rasa-x-rabbit"
                username: "user"
                password: ${RABBITMQ_PASSWORD}
                port: 5672
                queues:
                  - ${RABBITMQ_QUEUE}
      - ingress:
          enabled: false
      - extraEnv:
         - name: "RABBITMQ_QUEUE"
           value: rasa_production_events
         - name: "RABBITMQ_PASSWORD"
           valueFrom:
             secretKeyRef:
               name: rasa-x-rabbit
               key: rabbitmq-password

  - name: rasa-x
    chart: ../../../rasa-x-helm/charts/rasa-x/
