{{- define "rasa-bot.containers.env" -}}
{{- if and (eq (include "rasa-bot.endpoints.models.enabled" .) "true") .Values.applicationSettings.endpoints.models.token }}
- name: MODEL_SERVER_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ include "rasa-common.names.fullname" . }}
      key: model-server-token
{{- end }}
{{- if and (eq (include "rasa-bot.endpoints.trackerStore.enabled" .) "true") (not .Values.applicationSettings.endpoints.trackerStore.customConfiguration) (eq (include "rasa-common.psql.available" .) "true") }}
{{ include "rasa-common.psql.envs" . }}
{{- end }}
{{- if and (eq (include "rasa-bot.endpoints.lockStore.enabled" .) "true") (not .Values.applicationSettings.endpoints.lockStore.customConfiguration) (eq (include "rasa-common.redis.available" .) "true") }}
{{ include "rasa-common.redis.envs" . }}
{{- end }}
{{- if and (eq (include "rasa-bot.endpoints.eventBroker.enabled" .) "true") (not .Values.applicationSettings.endpoints.eventBroker.customConfiguration) (eq (include "rasa-common.rabbitmq.available" .) "true") }}
{{ include "rasa-common.rabbitmq.envs" . }}
{{- end }}
{{- if eq (include "rasa-bot.endpoints.action" .) "true" }}
{{ include "rasa-bot.actionServer.envs" . }}
{{- end }}
- name: "RASA_TELEMETRY_ENABLED"
  value: {{ .Values.applicationSettings.telemetry.enabled | quote }}
- name: "MPLCONFIGDIR"
  value: "/tmp/.matplotlib"
- name: "TF_CPP_MIN_LOG_LEVEL"
  value: "2"
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv }}
{{- end }}
{{- end -}}
