{{- define "rasa-bot.defaultModel.initContainer" -}}
- name: download-default-model
  image: "busybox"
  command: ["/bin/sh", "-c"]
  args:
    - cd /app/models/ && wget {{ .Values.applicationSettings.defaultModel }} -O model.tar.gz
  volumeMounts:
    - mountPath: /app/models
      name: models
{{- end -}}

{{- define "rasa-bot.defaultModel.initContainer.volumes" -}}
- name: models
  emptyDir: {}
{{- end -}}

{{- define "rasa-bot.defaultModel.initContainer.volumeMounts" -}}
- mountPath: /app/models
  name: models
{{- end -}}
