{{ if not .Values.applicationSettings.enterprise.useConfigEndpoint }}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "rasa-common.names.fullname" . }}
  labels:
    {{- include "rasa-common.labels.standard" . | nindent 4 }}
data:
  credentials: |
{{- if eq (include "rasa-bot.credentials.enabled" .) "true" }}
    {{- with .Values.applicationSettings.credentials.additionalChannelCredentials }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- if and .Values.applicationSettings.enterprise.enabled .Values.applicationSettings.enterprise.url }}
    rasa:
      url: {{ .Values.applicationSettings.enterprise.url }}/api
{{- end }}
  endpoints: |
{{- if eq (include "rasa-bot.endpoints.models.enabled" .) "true" }}
    models:
      url: {{ .Values.applicationSettings.endpoints.models.url }}
      token: ${MODEL_SERVER_TOKEN}
      wait_time_between_pulls: {{ .Values.applicationSettings.endpoints.models.waitTimeBetweenPulls }}
{{- else if and .Values.applicationSettings.enterprise.enabled .Values.applicationSettings.enterprise.url }}
    models:
      url: {{ .Values.applicationSettings.enterprise.url }}/api/projects/default/models/tags/{{ .Values.applicationSettings.enterprise.model.tag }}
      token: ${RASA_ENTERPRISE_TOKEN}
      wait_time_between_pulls: {{ .Values.applicationSettings.enterprise.model.waitTimeBetweenPulls }}
{{- end }}
{{- if eq (include "rasa-bot.endpoints.trackerStore.enabled" .) "true"  }}
    {{- if .Values.applicationSettings.endpoints.trackerStore.customConfiguration }}
    tracker_store:
      {{- toYaml .Values.applicationSettings.endpoints.trackerStore.customConfiguration | nindent 6 }}
    {{- else if eq (include "rasa-common.psql.available" .) "true" }}
    tracker_store:
      type: sql
      dialect: "postgresql"
      url: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      db: ${DB_DATABASE}
      {{- if .Values.applicationSettings.endpoints.trackerStore.useLoginDatabase }}
      login_db: ${DB_DATABASE}
      {{- end }}
    {{- end }}
{{- end }}
{{- if eq (include "rasa-bot.endpoints.lockStore.enabled" .) "true" }}
    {{- if .Values.applicationSettings.endpoints.lockStore.customConfiguration }}
    lock_store:
      {{- toYaml .Values.applicationSettings.endpoints.lockStore.customConfiguration | nindent 6 }}
    {{- else if eq (include "rasa-common.redis.available" .) "true" }}
    lock_store:
      type: "redis"
      url: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      db: {{ .Values.applicationSettings.endpoints.lockStore.database | quote }}
    {{- end }}
{{- end }}
{{- if eq (include "rasa-bot.endpoints.eventBroker.enabled" .) "true" }}
    {{- if .Values.applicationSettings.endpoints.eventBroker.customConfiguration }}
    event_broker:
      {{- toYaml .Values.applicationSettings.endpoints.eventBroker.customConfiguration | nindent 6 }}
    {{- else if eq (include "rasa-common.rabbitmq.available" .) "true" }}
    event_broker:
      type: "pika"
      url: ${RABBITMQ_HOST}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}
      port: ${RABBITMQ_PORT}
      queues:
        - ${RABBITMQ_QUEUE}
    {{- end }}
{{- end }}
{{- if eq (include "rasa-bot.endpoints.action" .) "true" }}
    action_endpoint:
      url: ${ACTION_SERVER_URL}
{{- end }}
    {{- with .Values.applicationSettings.endpoints.additionalEndpoints }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ end }}
