{{- if .Values.ingress.enabled -}}
{{- $fullName := include "rasa-common.names.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: {{ include "rasa-common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-core
  labels:
    {{- include "rasa-common.labels.standard" . | nindent 4 }}
    {{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /core/(.*)
            {{- if eq "true" (include "rasa-common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "rasa-common.ingress.backend" (dict "serviceName" (include "rasa-common.names.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
  {{- end }}
