
{{- if not .Values.applicationSettings.enterprise.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rasa-common.names.fullname" . }}
  labels:
    {{- include "rasa-common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  model-server-token: {{ default "MISSING" .Values.applicationSettings.endpoints.models.token | b64enc | quote }}
{{- end }}
