
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rasa-common.names.fullname" . }}
  labels:
    {{- include "rasa-common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  model-server-token: {{ default "MISSING" .Values.applicationSettings.endpoints.models.token | b64enc | quote }}
  rasa-x-token: {{ default "MISSING" .Values.applicationSettings.rasaX.token | b64enc | quote }}
  rasa-token: {{ default "MISSING" .Values.applicationSettings.token | b64enc | quote }}
  jwt-secret: {{ default "MISSING" .Values.applicationSettings.rasaX.jwtSecret | b64enc | quote }}
