
name: Continuous Integration
on:
  push:
    branches:
    - 'main'
    - '[0-9]+.[0-9]+.x'
    tags:
    - '**'
    paths:
      - "charts/**"
  pull_request:
    types: [opened, synchronize, labeled]
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.0

      # helm/chart-testing-action requires python version >= 3.7
      # see: https://github.com/helm/chart-testing-action/issues/65
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --config .github/.ct.yaml


  kubeval-chart:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://github.com/instrumenta/kubernetes-json-schema
        k8s:
          - v1.14.10
          - v1.16.4
          - v1.18.1
        chart:
          - rasa-bot
          - rasa-action-server
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.0

      - name: Render template
        run: |
          helm dep up charts/${{ matrix.chart }}
          helm template -f .github/kubeval.values.yaml charts/${{ matrix.chart }} > ${{ matrix.chart }}.yaml

      - name: Run kubeval
        uses: instrumenta/kubeval-action@5915e4adba5adccac07cb156b82e54c3fed74921
        env:
          KUBEVAL_SCHEMA_LOCATION: https://kubernetesjsonschema.dev/
        with:
          files: ${{ matrix.chart }}.yaml
          ignore_missing_schemas: true
