name: Release Charts

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.0

      - name: Helm dependency update
        run: |
          cd ./charts
          for x in `ls`; do helm dependency update ./${x}; done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
